#!/bin/sh

# Note: This script relies on the relevant directories being at the same level, as well as properly configured tracking branches

# TODO: Make these smarter, meaning if git pull doesn't result in any changes, don't install gems, run rake/make, or ./build.sh

cd ..

# update non-gem dirs
for DIR in 'opscode-chef' 'opscode-account' 'opscode-certificate' 'opscode-test' 'opscode-usermgmt'
do
    (echo $DIR ; cd $DIR && git fetch && git fetch --tags && git pull --rebase)
done

# update and install gems
for DIR in 'chef' 'mixlib-authentication' 'mixlib-authorization' 'mixlib-cli' 'mixlib-log' 'mixlib-config' 'opscode-rest' 'opscode-audit' 'ohai' 'couchrest'
do
    (echo $DIR ; cd $DIR && git fetch && git fetch --tags && git pull --rebase && sudo rake install)
done

# update authorization service
(export DIR='opscode-authz' ; echo $DIR ; cd $DIR && git fetch && git fetch --tags && git pull --rebase && make)

# update and install nginx
(export DIR='nginx-sysoev' ; echo $DIR ; cd $DIR && git fetch && git fetch --tags && git pull --rebase && sudo ./build.sh)
